# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MrYanG's blog
email: yangyonghai@wusongtech.com
description: 杨勇海的博客，学习认真活着
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://iamflowerdog.github.io" # the base hostname & protocol for your site
repository: https://github.com/iamflowerdog/iamflowerdog.github.io
twitter_username: yonghaiyang
github_username:  iamflowerdog

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
exclude: [node_modules, gulpfile.js]

# Pagination
paginate: 7
paginate_path: "page/:num"

plugins:
 - jekyll-sitemap
 - jekyll-paginate
